### ISSUE TITLE
Webhook issue 

### ISSUE THREAD

**Issue by IsoDevMate** [gh-actions-workflows/deploy-docker-render#1]
I unfortunately run into this error when i try to deploy my ghcr.io hosted image  to render.com the image builds up successfully but i then get this error when the github action try to deploy to render         here is  how i configuresd my CICD workflow  name: Render CI/CD

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build-and-deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Convert repository name to lowercase
        id: lowercase
        run: |
            echo "::set-output name=repo::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"
  
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
            context: .
            push: true
            tags: ghcr.io/${{ steps.lowercase.outputs.repo }}:latest
  
      - name: Expose image URL
        run: |
         echo "Image URL: ghcr.io/${{ steps.lowercase.outputs.repo }}:latest"
  
      - name: Set up environment variables
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DB_PORT: ${{ secrets.DB_PORT }}
          PORT: ${{ secrets.PORT }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        run: |
          echo "Environment variables are set."

          
      - name: Deploy Backend to Render
        uses: gh-actions-workflows/deploy-docker-render@v1.1
        with:
              deploy-hook: ${{ secrets.DEPLOY_HOOK_URL }}
              image-url: ghcr.io/${{ steps.lowercase.outputs.repo }}:latest
              render-api-key: ${{ secrets.RENDERAPI_KEY }}
              wait-for-deployment: true
    below is the error i get   Run gh-actions-workflows/deploy-docker-render@v1.1
Validating inputs...
Triggering deploy...
Error: Failed to trigger deploy: 400 - Bad Request
{"badrequest":"deploy hook cannot change the host, project, or image name. Only the digest or tag may be modified"}

**Comment by PedroHPAlmeida** [comment]
Hello @IsoDevMate!

Try using the `docker-repo-prefix` parameter providing the value `ghcr.io`. By default the action uses `docker.io`, hence the error "deploy hook cannot change the **host**, project, or image name".

See all action parameters in this link: https://github.com/gh-actions-workflows/deploy-docker-render/blob/master/action.yml.
